### ISSUE TITLE
Search button issue

### ISSUE THREAD

**Issue by abrown1982** [gasman/wagtail-generic-chooser#6]
Fantastic code, adds much needed functionality and documentation is clear.  

I have an example setup with all working, however when the "search" button is clicked after loading the "choose another" option the wagtail "Leave Site" warning is shown.  

If I select to "leave" I then get a JSON response:

`{
  "step": "choose",
  "html" "etc..."
}`

The search does work without the search button, however this seems to be something I cannot see an obvious fix to.

Thanks

**Comment by abrown1982** [comment]
I think the issue is line 38 in chooser-modal.js

Instead of:
`$('form.snippet-search', modal.body).on('submit', search);`

it should be:
`$('form.chooser-search', modal.body).on('submit', search);`

**Comment by gasman** [comment]
Fixed in #7
